package com.example.MyBookShopApp.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "author_file")
@ApiModel(description = "entity representing a author file")
public class AuthorFile {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private Integer id;

    @ApiModelProperty("random hash designed to identify the file when downloading\n")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String hash;

    @ApiModelProperty("file type")
    @Column(name = "type_id", columnDefinition = "VARCHAR(255) NOT NULL")
    private Integer typeId;

    @ApiModelProperty("path to the file")
    private String path;

    @ManyToOne
    @JoinColumn(name = "author_id", referencedColumnName = "id")
    private Author author;
}
