package com.example.MyBookShopApp.data;

import com.example.MyBookShopApp.data.book.Book;
import com.example.MyBookShopApp.data.book.Book2Author;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "authors")
@ApiModel(description = "data model of author enrity")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 1)
    private Integer id;

    @Column(columnDefinition = "varchar(255)")
    @ApiModelProperty("photo of author")
    private String photo;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("mnemonical identity sequence of characters")
    private String slug;

    @ApiModelProperty(value = "first name and last name of author", example = "Bob Blaskovits")
    private String name;

    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("author description text")
    private String description;

    @OneToMany(mappedBy = "author")
    @JsonIgnore
    public List<Book2Author> book2Authors;

    @ManyToMany(cascade = CascadeType.ALL)
    @JsonIgnore
    @JoinTable(name = "book2author",
            joinColumns = @JoinColumn(name = "author_id"),
            inverseJoinColumns = @JoinColumn(name = "book_id"))
    private List<Book> books;

    @Override
    public String toString() {
        return name;
    }
}
