package com.example.MyBookShopApp.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "document")
@ApiModel(description = "entity representing a document")
public class Document {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private Integer id;

    @Column(columnDefinition = "INT DEFAULT 0")
    @ApiModelProperty("serial number of the document (for display on the document list page), default 0")
    private int sortIndex;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("mnemonic code of the document displayed in the link to the document page")
    private String slug;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("document title")
    private String title;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty("document text in HTML format")
    private String text;

}
