package com.example.MyBookShopApp.data;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@Table(name = "message")
@ApiModel(description = "entity representing a message in the feedback form")
public class Message {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private Integer id;

    @Column(name = "time", columnDefinition = "DATE NOT NULL")
    @ApiModelProperty("date and time the message was sent")
    private LocalDateTime time;

    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private BookstoreUser user;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("user's email if user not logged in")
    private String email;

    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("user's name if user not logged in")
    private String name;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("Message subject")
    private String subject;

    @Column(columnDefinition = "TEXT NOT NULL")
    @ApiModelProperty("message's text")
    private String text;
}
