package com.example.MyBookShopApp.data;

import com.example.MyBookShopApp.data.book.BookType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.sql.Date;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@Table(name = "user_contact")
@ApiModel(description = "entity representing a user")
public class UserContact {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private Integer id;

    @ManyToOne
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private BookstoreUser user;

    @ApiModelProperty("contact type (phone or e-mail)")
    @Enumerated(EnumType.STRING)
    private EnumContactType type;

    @Column(columnDefinition = "INT ")//NOT NULL
    @ApiModelProperty("contact is confirmed = 1 and contact isn't confirmed = 0")
    private int approved;

    @ApiModelProperty("confirmation code")
    private String code;

    @Column(name = "code_time", columnDefinition = "TIMESTAMP")//NOT NULL
    @ApiModelProperty("date and time when the confirmation code was generated")
    private LocalDateTime codeTime;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("contact (e-mail or phone)")
    private String contact;
}
