package com.example.MyBookShopApp.data.book;

import com.example.MyBookShopApp.data.book.Book;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "book_rating")
@ApiModel(description = "entity book rating")
public class BookRating {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private int id;

    @Column(name = "rating", columnDefinition = "integer default 0")
    private int rating;

    @OneToMany(mappedBy = "bookRating", cascade = CascadeType.ALL)//
    @JsonIgnore
    private List<BookRatingGrade> bookRatingGradeList = new ArrayList<>();


    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "book_id", referencedColumnName = "id")
    @JsonIgnore
    private Book book;

    public Integer gradeSum() {
        int gradeSum = 0;
        for (BookRatingGrade bookRatingGrade : bookRatingGradeList) {
            gradeSum += bookRatingGrade.getCount();
        }
        return gradeSum;
    }

    public BookRating() {
    }
}
