package com.example.MyBookShopApp.data.book;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
@Setter
@Getter
@Entity
@Table(name = "book_file")
@ApiModel(description = "entity representing a book file")
public class BookFile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private Integer id;

    @ApiModelProperty("random hash designed to identify the file when downloading\n")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String hash;

    @ApiModelProperty("file type")
    @Column(name = "type_id", columnDefinition = "VARCHAR(255) NOT NULL")
    private Integer typeId;

    @ApiModelProperty("path to the file")
    private String path;

    @ManyToOne
    @JoinColumn(name = "book_id", referencedColumnName = "id")
    private Book book;

    public String getBookFileExtensionString() {
        return BookFileType.getExtensionStringByTypeId(typeId);
    }


}
