package com.example.MyBookShopApp.data.book;

import com.example.MyBookShopApp.data.Author;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "book2author")
@ApiModel(description = "linking authors to books")
public class Book2Author {

    @Id
    @ApiModelProperty("id generated by db automaticaly")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ManyToOne
    @JoinColumn(name = "book_id")
    @JsonIgnore
    private Book book;

    @ManyToOne
    @JoinColumn(name = "author_id")
    @JsonIgnore
    private Author author;

    @ApiModelProperty("author's serial number")
    @Column(name = "sort_index", columnDefinition = "INT NOT NULL DEFAULT 0")
    private int sortIndex;

}
