package com.example.MyBookShopApp.data.book;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "book_rating_grade")
@ApiModel(description = "entity book rating grade")
public class BookRatingGrade {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private int id;

    @Column(name = "count", columnDefinition = "integer default 0")
    private int count;

    @ManyToOne
    @JoinColumn(name="rating_id")
    @JsonIgnore
    private BookRating bookRating;

}
