package com.example.MyBookShopApp.data.book;

import com.example.MyBookShopApp.data.UserContact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "book2user_type")
@ApiModel(description = "entity representing a book2user_type")
public class Book2UserType {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private int id;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("binding type code")
    private String code;

    @Column(name = "type_name", columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty("binding type name")
    private String typeName;
}
