package com.example.MyBookShopApp.data.book;

import com.example.MyBookShopApp.data.BookstoreUser;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@Table(name = "book2user")
@ApiModel(description = "entity representing a book2user")
public class Book2User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private int id;

    @Column(name = "reg_time", columnDefinition = "DATE NOT NULL")
    @ApiModelProperty("date and time of book2user occurrence of binding")
    private LocalDateTime time;

    @ManyToOne
    @JoinColumn(name = "book_id")
    @JsonIgnore
    private Book book;

    @ManyToOne
    @JoinColumn(name = "user_id")
    @JsonIgnore
    private BookstoreUser user;

    @Column(name = "type_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("id book binding type to user")
    private int typeId;

}
