package com.example.MyBookShopApp.data.book;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name = "book2genre")
@ApiModel(description = "entity representing a book2genre")
public class Book2Genre {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automaticaly")
    private int id;

    @Column(name = "book_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("book ID")
    private int bookId;

    @Column(name = "genre_id", columnDefinition = "INT NOT NULL")
    @ApiModelProperty("genre ID")
    private int genreId;

}
